project:
  type: website

website:
  
  
  title: "WebGIS Assignment 3"
  navbar:
    search: true
    pinned: true
    right:
      - href: index.qmd
        text: Home
        icon: "house-door" 
        
      - about.qmd
      - href: letter.qmd
        text: Mayor Info
      
      - href: letter2.qmd
        text: Letter
        icon: "book" 
      - text: Menu
        menu: 
          - about.qmd
          - index.qmd
          - letter2.qmd
          - letter.qmd
      

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

